### ISSUE TITLE
Cannot load configuration

### ISSUE THREAD

**Issue by EdwardMoyse** [HSF/phoenix#276] opened 2021-04-16 13:47 UTC
Hi @9inpachi I hope this is just something messed up on my end, but I think I might have broken the configuration loading somehow... possibly related to my adding new options to the View menu?

If I try to save then immediately load a configuration it fails with:

```
core.js:6162 ERROR TypeError: firstElem.toArray is not a function
    at flatten (three.module.js:15593)
    at PureArrayUniform.setValueV4fArray [as setValue] (three.module.js:16108)
    at Function.push.nVqq.WebGLUniforms.upload (three.module.js:16456)
    at setProgram (three.module.js:24911)
    at WebGLRenderer.renderBufferDirect (three.module.js:23926)
    at renderObject (three.module.js:24504)
    at renderObjects (three.module.js:24477)
    at WebGLRenderer.render (three.module.js:24256)
    at EffectsManager.antialiasRender (effects-manager.ts:62)
    at ThreeManager.render (index.ts:173)
```

I'm really sorry if I've done something dumb, but do you have any idea?

**Comment by 9inpachi** [comment] 2021-04-16 14:22
I don't see anything in the stack that might be caused by your code. Seems to be an error in three.js internally - particularly in the render function. I'll try having a look.

**Comment by 9inpachi** [comment] 2021-04-16 14:27
Immediately saving the state and loading it seems to work perfectly fine. The view options aren't a part of the state configuration so that wouldn't be the cause anyway.

**Comment by 9inpachi** [comment] 2021-04-27 18:29
@EdwardMoyse Is this okay now?

**Comment by 9inpachi** [comment] 2021-06-12 11:02
Closing because can't reproduce.

**Closed by 9inpachi** 2021-06-12 11:02 UTC
Labels: bug
